spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gaeme
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting

#jwt.secret: chatter1chatter1chatter1chatter1
#
#oauth.redirect_url: 192.168.219.104
#oauth.kakao.client_id: c4587d8bd2cad9c8bb3cc1a95c5c2847
#oauth.naver.client_id: hiayQt_RafO3cYGplKx9
#oauth.naver.client_secret: PXrCaNyOPL